FROM bram2473/haystack-nvidia:0.0.1

ADD blockNetwork.policy blockNetwork.policy 
ADD blind-webserver-0.0.1.jar blind-webserver-0.0.1.jar
ADD haystack.jar haystack.jar

ENTRYPOINT java -jar blind-webserver-0.0.1.jar
